### ISSUE TITLE
Documentation Quickstart is out of date for 1.21.0

### ISSUE THREAD

**Issue by SyoAnd** [riscv/riscof#9]
When running _riscof testlist_  and _riscof run_ **suite** and **env** is required.
I fixed it by first running **riscof arch-test** 
then running above comands with 
**--suite=riscv-arch-test --env=riscv-arch-test/riscv-test-suite/env**

Which seems to be running fine. but i receive the following errors..

`     
......

INFO | [--root--]: Generating database for suite: /home/user/riscof/riscv-arch-test
  WARNING | [--riscof.dbgen--]: /home/user/riscof/riscv-arch-test/riscv-test-env/v/entry.S:ISA not specified.
  WARNING | [--riscof.dbgen--]: /home/user/riscof/riscv-arch-test/riscv-target/OpenHW/device/cv32e40p/handler.S:ISA not specified.
  WARNING | [--riscof.dbgen--]: /home/user/riscof/riscv-arch-test/riscv-target/ibex/device/rv32imc/handler.S:ISA not specified.
  WARNING | [--riscof.dbgen--]: /home/user/riscof/riscv-arch-test/riscv-target/ri5cy/device/rv32imc/handler.S:ISA not specified.
     INFO | [--root--]: Database File Generated: /home/user/riscof/riscof_work/database.yaml
.....
`

And when running riscof run ....

`
  WARNING | [--riscof.utils--]: In file included from /home/user/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/C/src/cadd-01.S:19:
/home/user/riscof/riscv-arch-test/riscv-test-suite/env/arch_test.h:14: warning: "TEST_CASE_1" redefined
 #define TEST_CASE_1
 
<command-line>: note: this is the location of the previous definition
In file included from /home/user/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/C/src/caddi-01.S:19:
/home/user/riscof/riscv-arch-test/riscv-test-suite/env/arch_test.h:14: warning: "TEST_CASE_1" redefined
 #define TEST_CASE_1
 
<command-line>: note: this is the location of the previous definition
In file included from /home/user/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/C/src/caddi16sp-01.S:19:
/home/user/riscof/riscv-arch-test/riscv-test-suite/env/arch_test.h:14: warning: "TEST_CASE_1" redefined
 #define TEST_CASE_1

etc.
`

**Comment by neelgala** [comment]
the suite argument should point to the riscv-test-suite/rv32i_m or riscv-test-suite/rv64i_m directory as mentioned in the doc [here](https://riscof.readthedocs.io/en/stable/arch-tests.html#running-tests-with-riscof). So the command sequence should be :

```
riscof arch-test
riscor run --suite=riscv-arch-test/riscv-test-suite/rv64i_m/ --env=riscv-arch-test/riscv-test-suite/env
```
By default riscof parses recursively in the path pointed by `--suite`. It looks for any/all .S files and checks if they match the test-format spec. If not they will be skipped from the database of tests. The warning you got from dbgen are precisely those - its skipping the target specific assembly files it encountered.

The other warning you get during the `run` command is because all tests in the riscv-arch-test are configured to [enable the same TEST_CASE_1](https://github.com/riscv/riscv-arch-test/blob/20f58fc63eaa60d56036690ca40d9008a3942ea8/riscv-test-suite/env/arch_test.h#L14). This macro is also separately set at compile time by riscof, hence the warning on redefinition. Once the riscv-arch-test moves to riscof, that warning should also disappear. Removing it now, will cause the current riscv-arch-test framework to fail.
